name: Deploy reach.cogzi.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Debug SSH connection
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "Key: $EC2_UEC2_SSH_KEY" 
          echo "Host: $EC2_HOST"
          echo "User: $EC2_USER"

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/reach.cogzi.io/releases/$(date +'%Y%m%d%H%M%S')"
          debug: true

      - name: Finalize deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          debug: true
          script: |
            RELEASE_DIR="/var/www/reach.cogzi.io/releases"
            CURRENT_LINK="/var/www/reach.cogzi.io/current"
            LATEST_RELEASE=$(ls -t $RELEASE_DIR | head -n 1)

            ln -sfn "$RELEASE_DIR/$LATEST_RELEASE" "$CURRENT_LINK"
            pm2 restart reach-app

  rollback:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()
    steps:
      - name: Rollback to previous release
        uses: appleboy/ssh-action@master
        with:
          host: ${{  secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          debug: true
          script: |
            RELEASE_DIR="/var/www/reach.cogzi.io/releases"
            CURRENT_LINK="/var/www/reach.cogzi.io/current"

            PREV_RELEASE=$(ls -t $RELEASE_DIR | sed -n 2p)
            if [ -z "$PREV_RELEASE" ]; then
              echo "No previous release found!"
              exit 1
            fi

            ln -sfn "$RELEASE_DIR/$PREV_RELEASE" "$CURRENT_LINK"
            pm2 restart reach-app
            echo "Rolled back to $PREV_RELEASE"
